In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
import numpy as np


In [ ]:
import numpy as np
a=np.array([1,2,3])

In [ ]:
np.arange(4)


array([0, 1, 2, 3])

In [ ]:
np.arange(2,9,2)


array([2, 4, 6, 8])

In [ ]:
arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.random.rand(2)

array([0.02902878, 0.64894636])

In [ ]:
np.random.rand(5,5)

array([[0.01228763, 0.61605614, 0.46403691, 0.55853596, 0.45589322],
       [0.43759273, 0.30233547, 0.11240564, 0.43267218, 0.93256981],
       [0.4954377 , 0.5230509 , 0.0953196 , 0.46483373, 0.9075864 ],
       [0.44562164, 0.81675949, 0.12539721, 0.90043766, 0.15703114],
       [0.82773082, 0.85435066, 0.27377027, 0.93744193, 0.68459147]])

In [ ]:
np.random.randn(2)

array([0.19250868, 0.72314623])

In [ ]:
np.random.randint(1,100)

79

In [ ]:
np.random.randint(1,100,20)

array([60, 61,  4, 39, 43, 90, 63, 26, 43, 86, 83, 79, 83, 32, 47, 23, 53,
       69, 17, 51])

In [ ]:
np.random.seed()

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[8]

8

In [ ]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:7]=30
arr

array([30, 30, 30, 30, 30, 30, 30,  7,  8,  9, 10])

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_arr = arr[0:5]
slice_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1][0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
arr_2d[:,2]

array([15, 30, 45])

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [ ]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
arr=np.(10,50,2)

SyntaxError: ignored

In [ ]:
#3x3 identity matrix


In [ ]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])